# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Announcement of confirmed patients today

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 2 * * *'

jobs:
    start:
        runs-on: ubuntu-16.04
        strategy:
            matrix:
                node-version: [12.x]
        env:
            OPEN_API_ACCESS_KEY: ${{secrets.OPEN_API_SECRET}}
            SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
            SLACK_CHANNEL_ID: ${{secrets.SLACK_CHANNEL_ID}}
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.JS
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}
            - run: |
                npm install
                npm start
